name: 'Tests and formater'

on: push

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
    - uses: mstksg/setup-stack@v1
        
    - name: Build
      run: make build
    - name: Run tests and formater
      run: make lint
